version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/hospital/:/var/www/hospital
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    networks:
      - app-network
    depends_on:
      - hospital

  hospital:
    container_name: hospital
    build:
      context: apps/hospital
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: hospital
      SERVICE_TAGS: dev
    working_dir: /var/www/hospital
    stdin_open: true
    volumes:
      - ./apps/hospital/:/var/www/hospital
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      dockerfile: ./docker/mysql/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --init-file /etc/mysql/init.sql
    environment:
      MYSQL_DATABASE: 'hospital'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/init.sql:/etc/mysql/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local